#syntax=docker/dockerfile:1.7.0-labs

FROM rustlang/rust:nightly-alpine as installer

RUN \
  apk update \
  && apk add --no-cache curl bash libc-dev binaryen \
  && curl --proto '=https' --tlsv1.3 -LsSf https://github.com/leptos-rs/cargo-leptos/releases/latest/download/cargo-leptos-installer.sh | sh \
  && curl --proto '=https' --tlsv1.3 -LsSf https://bun.com/install | bash -s "bun-v1.2.18" \
  && cargo install --no-default-features --debug cargo-make

# FIXME: le faire fonctionner lol
# COPY rust-toolchain.toml .
# RUN rustup toolchain install --no-self-update --profile minimal

RUN rustup target add wasm32-unknown-unknown

FROM rust as planner

# continuer https://corrode.dev/blog/tips-for-faster-rust-compile-times/
WORKDIR /project
RUN cargo install cargo-chef
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM rust as cacher
WORKDIR /project
RUN cargo install cargo-chef
COPY --from=planner /project/recipe.json /project/recipe.json
RUN cargo +nightly chef cook --release --recipe-path recipe.json

FROM installer as builder

WORKDIR /project

ENV PATH="/root/.bun/bin:$PATH"

COPY --from=cacher /project/target /project/target
# COPY --from=cacher /usr/local/cargo /usr/local/cargo

## `local.db` required by SQLx for macros
RUN \
  --mount=type=bind,readonly,source=./.env,target=/project/.env \
  --mount=type=bind,readonly,source=./Cargo.toml,target=/project/Cargo.toml \
  --mount=type=bind,readonly,source=./Cargo.lock,target=/project/Cargo.lock \
  --mount=type=bind,readonly,source=./package.json,target=/project/package.json \
  --mount=type=bind,readonly,source=./bun.lock,target=/project/bun.lock \
  --mount=type=bind,readonly,source=./Makefile.toml,target=/project/Makefile.toml \
  --mount=type=bind,readonly,source=./makefiles,target=/project/makefiles \
  --mount=type=bind,readonly,source=./assets,target=/project/assets \
  --mount=type=bind,readonly,source=./project_data,target=/project/project_data \
  --mount=type=bind,readonly,source=./tailwind,target=/project/tailwind \
  --mount=type=bind,readonly,source=./local.db,target=/project/local.db \
  --mount=type=bind,readonly,source=./src,target=/project/src \
  cargo make --profile release-ci build \
  && mkdir dist/ \
  && mv target/release/lyre_web dist/ \
  && mv target/site dist/

FROM scratch as runner

WORKDIR /app

COPY .env .
COPY Cargo.toml .

COPY --parents project_data/**/*.md .
COPY local.db .

COPY --from=builder /project/dist/lyre_web /app/
COPY --from=builder /project/dist/site /app/site

ENV RUST_LOG="info"
ENV LEPTOS_SITE_ADDR="0.0.0.0:8507"
ENV LEPTOS_SITE_ROOT=./site

EXPOSE 8507
CMD ["/app/lyre_web"]
